-- 05-advanced-querying / ctes.sql
-- Database: Chinook | MySQL 8.0.42

USE chinook;

-- Q1: List each invoice along with its total, using a CTE instead of a subquery.
WITH invoice_totals AS (
    SELECT InvoiceId, CustomerId, InvoiceDate, Total
    FROM invoice
)
SELECT * FROM invoice_totals
ORDER BY Total DESC;


-- Q2: Find the total revenue generated by each customer, and filter to only customers who've spent over $40 .
WITH customer_revenue AS (
    SELECT CustomerId, SUM(Total) AS total_spent
    FROM invoice
    GROUP BY CustomerId
)
SELECT * FROM customer_revenue
WHERE total_spent > 40
ORDER BY total_spent DESC;


-- Q3: Find the top 10 highest-revenue tracks, using two CTEs chained together — one to calculate revenue per track, another to rank them.
WITH track_revenue AS (
    SELECT il.TrackId, t.Name AS track_name,
           SUM(il.UnitPrice * il.Quantity) AS revenue
    FROM invoiceline AS il
    INNER JOIN track AS t ON il.TrackId = t.TrackId
    GROUP BY il.TrackId, t.Name
),
ranked_tracks AS (
    SELECT track_name, revenue,
           RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
    FROM track_revenue
)
SELECT * FROM ranked_tracks
WHERE revenue_rank <= 10;


-- Q4: Find invoices with a total above the average invoice total across the whole store (CTE replacing a repeated subquery).
WITH avg_invoice AS (
    SELECT AVG(Total) AS avg_total FROM invoice
)
SELECT i.InvoiceId, i.CustomerId, i.Total
FROM invoice AS i, avg_invoice
WHERE i.Total > avg_invoice.avg_total
ORDER BY i.Total DESC;


-- Q5: Find total revenue generated per music genre, ordered highest to lowest.
WITH genre_revenue AS (
    SELECT g.Name AS genre_name,
           SUM(il.UnitPrice * il.Quantity) AS revenue
    FROM invoiceline AS il
    INNER JOIN track AS t ON il.TrackId = t.TrackId
    INNER JOIN genre AS g ON t.GenreId = g.GenreId
    GROUP BY g.Name
)
SELECT * FROM genre_revenue
ORDER BY revenue DESC;


-- Q6: For each employee (support rep), count how many customers they support and the total revenue those customers generated.
WITH rep_performance AS (
    SELECT e.EmployeeId,
           CONCAT(e.FirstName, ' ', e.LastName) AS employee_name,
           COUNT(DISTINCT c.CustomerId) AS customers_supported,
           SUM(i.Total) AS total_revenue
    FROM employee AS e
    INNER JOIN customer AS c ON e.EmployeeId = c.SupportRepId
    INNER JOIN invoice AS i ON c.CustomerId = i.CustomerId
    GROUP BY e.EmployeeId, e.FirstName, e.LastName
)
SELECT * FROM rep_performance
ORDER BY total_revenue DESC;


-- Q7: Calculate the running total of monthly revenue over time, using a CTE to first aggregate by month, then a window function on top of it.
WITH monthly_revenue AS (
    SELECT YEAR(InvoiceDate) AS invoice_year,
           MONTH(InvoiceDate) AS invoice_month,
           SUM(Total) AS month_total
    FROM invoice
    GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
)
SELECT invoice_year, invoice_month, month_total,
       SUM(month_total) OVER (ORDER BY invoice_year, invoice_month) AS running_total
FROM monthly_revenue
ORDER BY invoice_year, invoice_month;


-- Q8: Find the top-selling artist by total revenue, using a CTE to simplify what would otherwise be a deeply nested multi-join.
WITH artist_revenue AS (
    SELECT ar.ArtistId, ar.Name AS artist_name,
           SUM(il.UnitPrice * il.Quantity) AS revenue
    FROM artist AS ar
    INNER JOIN album AS al ON ar.ArtistId = al.ArtistId
    INNER JOIN track AS t ON al.AlbumId = t.AlbumId
    INNER JOIN invoiceline AS il ON t.TrackId = il.TrackId
    GROUP BY ar.ArtistId, ar.Name
)
SELECT * FROM artist_revenue
ORDER BY revenue DESC
LIMIT 10;

-- End of ctes.sql
